name: cmake-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: IDA ${{ matrix.idasdk.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-24.04
        - ubuntu-22.04
        - macos-15-intel
        - macos-15
        - windows-2022
        idasdk:
          - version: "9.0"
            type: hcli
            hcli_tag: "release/9.0/sdk-and-utilities/idasdk90.zip"
            zip_filename: "idasdk90.zip"
            subdir: "idasdk90"
          - version: "9.1"
            type: hcli
            hcli_tag: "release/9.1/sdk-and-utilities/idasdk91.zip"
            zip_filename: "idasdk91.zip"
            subdir: "idasdk91"
          - version: "9.2"
            type: hcli
            hcli_tag: "release/9.2/sdk-and-utilities/idasdk92.zip"
            zip_filename: "idasdk92.zip"
            subdir: "src"
          - version: "9.3"
            type: oss
            repo_tag: "v9.3"
            subdir: "src"

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v6

    - name: Checkout bindiff repository
      uses: actions/checkout@v6
      with:
        repository: google/bindiff
        ref: 156cc32a39863e8795fbbe05da113f005f72752b
        path: bindiff
        submodules: recursive

    - name: Checkout binexport repository
      uses: actions/checkout@v6
      with:
        repository: google/binexport
        ref: 644786690fcb6bcf6d42a76e7d8b65056176054d
        path: binexport
        submodules: recursive

    - name: Apply patch (bindiff)
      shell: bash
      working-directory: bindiff
      run: |
        git apply ../patches/bindiff-compile_abseil_mutexlock.patch
        git apply ../patches/bindiff-i64_matches_ida_exe.patch

    - name: Apply patch (binexport)
      shell: bash
      working-directory: binexport
      run: |
        git apply ../patches/binexport-cmake.patch

    - name: Get idasdk (hcli)
      if: matrix.idasdk.type == 'hcli'
      shell: bash
      run: |
        mkdir idasdk
        curl -LsSf https://hcli.docs.hex-rays.com/install | sh
        hcli download "${{ matrix.idasdk.hcli_tag }}"
        unzip -q "${{ matrix.idasdk.zip_filename }}" -d idasdk/
      env:
        HCLI_API_KEY: ${{ secrets.HCLI_API_KEY }}

    - name: Get idasdk (oss)
      if: matrix.idasdk.type == 'oss'
      uses: actions/checkout@v6
      with:
        repository: HexRaysSA/ida-sdk
        ref: ${{ matrix.idasdk.repo_tag }}
        path: idasdk
        submodules: recursive

    - name: Install ninja-build tool
      uses: aseprite/get-ninja@main

    - name: Enable Developer Command Prompt (Windows)
      if: matrix.os == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Enable mold linker (Linux)
      if: matrix.os == 'ubuntu-24.04' || matrix.os == 'ubuntu-22.04'
      uses: rui314/setup-mold@v1

    - name: Install boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        boost_version: 1.86.0
        platform_version: ${{ matrix.os == 'windows-2022' && '2022' || matrix.os == 'ubuntu-24.04' && '22.04' || matrix.os == 'ubuntu-22.04' && '22.04' || matrix.os == 'macos-15-intel' && '13' || matrix.os == 'macos-15' && '15' }}
        toolset: ${{ matrix.os == 'windows-2022' && 'msvc' || matrix.os == 'ubuntu-24.04' && 'gcc' || matrix.os == 'ubuntu-22.04' && 'gcc' || matrix.os == 'macos-15-intel' && 'clang' || matrix.os == 'macos-15' && 'clang' }}
        arch: ${{ matrix.os != 'macos-15' && 'x86' || matrix.os == 'macos-15' && 'aarch64' }}

    - name: Configure CMake
      shell: bash
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: |
        mkdir -p build/out
        cmake -S bindiff -B build/out -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          -DCMAKE_INSTALL_PREFIX=build/out \
          -DBINDIFF_BINEXPORT_DIR=binexport \
          "-DIdaSdk_ROOT_DIR=${PWD}/idasdk/${{ matrix.idasdk.subdir }}" \
          -DBoost_INCLUDE_DIR="${{ steps.install-boost.outputs.BOOST_ROOT }}/include" \
          -DBoost_LIBRARY_DIRS="${{ steps.install-boost.outputs.BOOST_ROOT }}/lib"

    - name: Build
      working-directory: build/out
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test
      working-directory: build/out
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: BinDiff-IDA-${{ matrix.idasdk.version }}-${{ matrix.os }}
        path: |
          build/out/bindiff
          build/out/bindiff.exe
          build/out/ida/bindiff*
          build/out/tools/bindiff*

    - name: Configure CMake (binexport)
      shell: bash
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: |
        cmake -S binexport -B build/out/_deps/binexport-build -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          -DCMAKE_INSTALL_PREFIX=build/out/_deps/binexport-build \
          -DBINEXPORT_ENABLE_IDAPRO=ON \
          -DBINEXPORT_ENABLE_BINARYNINJA=ON \
          "-DIdaSdk_ROOT_DIR=${PWD}/idasdk/${{ matrix.idasdk.subdir }}" \
          -DBoost_INCLUDE_DIR="${{ steps.install-boost.outputs.BOOST_ROOT }}/include" \
          -DBoost_LIBRARY_DIRS="${{ steps.install-boost.outputs.BOOST_ROOT }}/lib"

    - name: Build (binexport)
      working-directory: build/out/_deps/binexport-build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test (binexport)
      working-directory: build/out/_deps/binexport-build
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts (binexport)
      uses: actions/upload-artifact@v7
      with:
        name: BinExport-IDA-${{ matrix.idasdk.version }}-${{ matrix.os }}
        path: |
          build/out/_deps/binexport-build/binaryninja/binexport*
          build/out/_deps/binexport-build/ida/binexport*
          build/out/_deps/binexport-build/tools/binexport2dump*
